### ISSUE TITLE
Issue with portainer agent docker image

### ISSUE THREAD

**Issue by dudeisbrendan03** [portainer/docker-images#2] opened 2018-08-17 21:26 UTC
Issue occurs on `portainer/agent:latest`

Error is as follows:
```
igbkxihscuyw: failed to create new osl sandbox: namespace creation reexec command failed…
```
Was created by running:
```
$ docker swarm init
[removed]
$ docker network create --driver overlay --attachable portainer_agent_network
[removed - ID of created network]
$ docker service create \
>     --name portainer_agent \
>     --network portainer_agent_network \
>     -e AGENT_CLUSTER_ADDR=tasks.portainer_agent \
>     --mode global \
>     --constraint 'node.platform.os == linux' \
>     --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
>     --mount type=bind,src=//var/lib/docker/volumes,dst=/var/lib/docker/volumes \
>     portainer/agent
[remvoed - ID of service]
robpryxyyr23: running   [==================================================>]
9voqn3ayuggd: running   [==================================================>]
igbkxihscuyw: failed to create new osl sandbox: namespace creation reexec command failed…
```
Bottom line loops from: pending>assigned>accepted>preparing then after preparing I get failed to ...

Expected result is that the service is created and I just get the ID and resources as an output

**Comment by deviantony** [comment] 2018-08-18 06:31
It's probably related to your Docker setup and not to the Docker image itself. I've been doing some quick search online about this error and it was reported by other users before but without a clear root cause/solution.

Closing as I believe that this is not related to the Portainer agent image.

**Closed as completed by deviantony** 2018-08-18 06:31 UTC
